/**
 * sync.ts — Effikit keyword index auto-updater
 *
 * Scans all .ts files in craft/ and mind/ for @keywords tags,
 * then regenerates the keyword tables in keywords.md.
 *
 * Usage: npx ts-node sync.ts
 */

import * as fs from "fs";
import * as path from "path";

// ─── Types ───────────────────────────────────────────────────────────────────

interface FileMetadata {
  filePath: string;
  relativePath: string;
  keywords: string[];
  domain: string;
  useWhen: string;
  notWhen: string;
}

interface SyncResult {
  scanned: number;
  indexed: number;
  skipped: number;
  errors: string[];
}

// ─── Config ──────────────────────────────────────────────────────────────────

const ROOT_DIR = path.resolve(__dirname);
const KEYWORDS_FILE = path.join(ROOT_DIR, "keywords.md");
const SCAN_DIRS = ["craft", "mind"];

const TAG_PATTERNS = {
  keywords: /@keywords\s+(.+)/,
  domain: /@domain\s+(.+)/,
  useWhen: /@use-when\s+(.+)/,
  notWhen: /@not-when\s+(.+)/,
} as const;

// ─── File Scanner ─────────────────────────────────────────────────────────────

function extractTags(content: string): Partial<FileMetadata> {
  const result: Partial<FileMetadata> = {};

  for (const [key, pattern] of Object.entries(TAG_PATTERNS)) {
    const match = content.match(pattern);
    if (match) {
      const value = match[1].trim();
      if (key === "keywords") {
        result.keywords = value.split(",").map((k) => k.trim()).filter(Boolean);
      } else {
        (result as Record<string, string>)[key] = value;
      }
    }
  }

  return result;
}

function scanDirectory(dirPath: string): FileMetadata[] {
  const results: FileMetadata[] = [];

  if (!fs.existsSync(dirPath)) return results;

  const entries = fs.readdirSync(dirPath, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);

    if (entry.isDirectory()) {
      // Recurse into subdirectories
      results.push(...scanDirectory(fullPath));
    } else if (entry.isFile() && entry.name.endsWith(".ts")) {
      const content = fs.readFileSync(fullPath, "utf-8");
      const tags = extractTags(content);

      if (tags.keywords && tags.keywords.length > 0) {
        const relativePath = path.relative(ROOT_DIR, fullPath).replace(/\\/g, "/");
        results.push({
          filePath: fullPath,
          relativePath,
          keywords: tags.keywords,
          domain: tags.domain ?? "unknown",
          useWhen: tags.useWhen ?? "",
          notWhen: tags.notWhen ?? "",
        });
      }
    }
  }

  return results;
}

// ─── Markdown Generator ───────────────────────────────────────────────────────

function groupByDirectory(files: FileMetadata[]): Map<string, FileMetadata[]> {
  const groups = new Map<string, FileMetadata[]>();

  for (const file of files) {
    // Group by top-level directory (craft or mind) + immediate subdirectory
    const parts = file.relativePath.split("/");
    const groupKey = parts.slice(0, 2).join("/");

    const existing = groups.get(groupKey) ?? [];
    existing.push(file);
    groups.set(groupKey, existing);
  }

  return groups;
}

function generateMarkdownSection(
  sectionTitle: string,
  files: FileMetadata[]
): string {
  if (files.length === 0) return "";

  const groups = groupByDirectory(files);
  let output = `## ${sectionTitle} — Auto-Generated Index\n\n`;
  output += `> Generated by sync.ts on ${new Date().toISOString().split("T")[0]}\n\n`;

  for (const [groupKey, groupFiles] of Array.from(groups.entries()).sort()) {
    const [topDir, subDir] = groupKey.split("/");
    output += `### ${topDir}/${subDir}\n\n`;
    output += `| Keywords | File | Use When |\n`;
    output += `|----------|------|----------|\n`;

    for (const file of groupFiles) {
      const keywords = file.keywords.join(", ");
      const useWhen = file.useWhen || file.domain;
      output += `| ${keywords} | \`${file.relativePath}\` | ${useWhen} |\n`;
    }

    output += "\n";
  }

  return output;
}

function buildUpdatedKeywords(
  originalContent: string,
  craftFiles: FileMetadata[],
  mindFiles: FileMetadata[]
): string {
  // Find the auto-generated section marker and replace it, or append
  const autoGenMarker = "<!-- AUTO-GENERATED: sync.ts -->";
  const autoGenEnd = "<!-- END AUTO-GENERATED -->";

  const craftSection = generateMarkdownSection("CRAFT", craftFiles);
  const mindSection = generateMarkdownSection("MIND", mindFiles);

  const autoGenContent = [
    autoGenMarker,
    "",
    craftSection,
    mindSection,
    autoGenEnd,
  ].join("\n");

  if (originalContent.includes(autoGenMarker)) {
    // Replace existing auto-gen section
    const startIdx = originalContent.indexOf(autoGenMarker);
    const endIdx = originalContent.indexOf(autoGenEnd);

    if (endIdx !== -1) {
      return (
        originalContent.slice(0, startIdx) +
        autoGenContent +
        originalContent.slice(endIdx + autoGenEnd.length)
      );
    }
  }

  // Append auto-gen section to end of file
  return originalContent.trimEnd() + "\n\n---\n\n" + autoGenContent + "\n";
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function sync(): SyncResult {
  const result: SyncResult = { scanned: 0, indexed: 0, skipped: 0, errors: [] };

  console.log("🔄 Effikit sync starting...\n");

  // Scan craft and mind directories
  const craftFiles: FileMetadata[] = [];
  const mindFiles: FileMetadata[] = [];

  for (const dir of SCAN_DIRS) {
    const dirPath = path.join(ROOT_DIR, dir);

    if (!fs.existsSync(dirPath)) {
      console.warn(`  ⚠️  Directory not found: ${dir}/`);
      continue;
    }

    const files = scanDirectory(dirPath);
    result.scanned += files.length;

    // Count files without tags as skipped
    const allTs = getAllTsFiles(dirPath);
    result.skipped += allTs.length - files.length;

    if (dir === "craft") craftFiles.push(...files);
    if (dir === "mind") mindFiles.push(...files);
  }

  result.indexed = craftFiles.length + mindFiles.length;

  // Read existing keywords.md
  let originalContent = "";
  if (fs.existsSync(KEYWORDS_FILE)) {
    originalContent = fs.readFileSync(KEYWORDS_FILE, "utf-8");
  }

  // Generate updated content
  const updatedContent = buildUpdatedKeywords(originalContent, craftFiles, mindFiles);

  // Write back
  fs.writeFileSync(KEYWORDS_FILE, updatedContent, "utf-8");

  // Report
  console.log(`  ✅ Scanned: ${result.scanned} TypeScript files`);
  console.log(`  ✅ Indexed: ${result.indexed} files with @keywords tags`);

  if (result.skipped > 0) {
    console.log(`  ⚠️  Skipped: ${result.skipped} files missing @keywords tag`);
  }

  if (result.errors.length > 0) {
    console.log(`\n  ❌ Errors:`);
    result.errors.forEach((e) => console.log(`     ${e}`));
  }

  console.log(`\n✨ keywords.md updated successfully.\n`);

  return result;
}

function getAllTsFiles(dirPath: string): string[] {
  const results: string[] = [];

  if (!fs.existsSync(dirPath)) return results;

  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      results.push(...getAllTsFiles(fullPath));
    } else if (entry.isFile() && entry.name.endsWith(".ts")) {
      results.push(fullPath);
    }
  }

  return results;
}

// ─── Run ──────────────────────────────────────────────────────────────────────

sync();
